title: The Perfect Workspace
email: info@danilosierra.com
description: > # this means to ignore newlines until "baseurl:"
  Looking for the utopic elements of the perfect office.
baseurl: "/Workspace" # the subpath of your site, e.g. /blog/
url: "http://danilosierrac.github.io/" # the base hostname & protocol for your site
twitter_username: bootsbosley
github_username:  danilosierrac


safe: true
markdown: kramdown